# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\realpro\pwq.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(802, 596)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.textBrowser = QtGui.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(520, 20, 256, 192))
        self.textBrowser.setStyleSheet(_fromUtf8("border-image: url(:/pic/2013081311212946468.jpg);"))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 220, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 220, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(520, 220, 101, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.radioButton = QtGui.QRadioButton(self.centralWidget)
        self.radioButton.setGeometry(QtCore.QRect(520, 260, 89, 16))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_2.setGeometry(QtCore.QRect(520, 290, 89, 16))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 260, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 260, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.centralWidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 510, 31, 31))
        self.graphicsView_2.setStyleSheet(_fromUtf8("border-image: url(:/pic/tx.png);"))
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.centralWidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 380, 31, 31))
        self.graphicsView_3.setStyleSheet(_fromUtf8("border-image: url(:/pic/baidu.png);"))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.graphicsView_4 = QtGui.QGraphicsView(self.centralWidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(10, 430, 31, 31))
        self.graphicsView_4.setStyleSheet(_fromUtf8("border-image: url(:/pic/tb1.png);"))
        self.graphicsView_4.setObjectName(_fromUtf8("graphicsView_4"))
        self.graphicsView_5 = QtGui.QGraphicsView(self.centralWidget)
        self.graphicsView_5.setGeometry(QtCore.QRect(10, 470, 31, 31))
        self.graphicsView_5.setStyleSheet(_fromUtf8("border-image: url(:/pic/11.png);"))
        self.graphicsView_5.setObjectName(_fromUtf8("graphicsView_5"))
        self.pushButton_5 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.centralWidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 20, 421, 291))
        self.textBrowser_2.setStyleSheet(_fromUtf8(""))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.pushButton_6 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 360, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 520, 75, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 550, 75, 23))
        self.pushButton_8.setStyleSheet(_fromUtf8("border-image: url(:/pic/tz.png);"))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_9.setGeometry(QtCore.QRect(114, 540, 31, 23))
        self.pushButton_9.setStyleSheet(_fromUtf8("border-image: url(:/pic/syq.png);"))
        self.pushButton_9.setText(_fromUtf8(""))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_10.setGeometry(QtCore.QRect(230, 540, 31, 23))
        self.pushButton_10.setStyleSheet(_fromUtf8("border-image: url(:/pic/xyq.jpg);"))
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.centralWidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(80, 330, 241, 151))
        self.textBrowser_3.setStyleSheet(_fromUtf8("border-image: url(:/pic/save.png);"))
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 490, 241, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(520, 530, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.centralWidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(520, 320, 261, 191))
        self.textBrowser_4.setStyleSheet(_fromUtf8("border-image: url(:/pic/exl.png);"))
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(580, 530, 191, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_11 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_11.setGeometry(QtCore.QRect(610, 570, 75, 23))
        self.pushButton_11.setStyleSheet(_fromUtf8(""))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_12.setGeometry(QtCore.QRect(520, 570, 75, 23))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 802, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuWenjian = QtGui.QMenu(self.menuBar)
        self.menuWenjian.setObjectName(_fromUtf8("menuWenjian"))
        self.menuBangzhu = QtGui.QMenu(self.menuBar)
        self.menuBangzhu.setObjectName(_fromUtf8("menuBangzhu"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionDakaitupian = QtGui.QAction(MainWindow)
        self.actionDakaitupian.setCheckable(False)
        self.actionDakaitupian.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pic/wallpaper.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDakaitupian.setIcon(icon)
        self.actionDakaitupian.setObjectName(_fromUtf8("actionDakaitupian"))
        self.actionDakaiexcel = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pic/adaptive_design.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDakaiexcel.setIcon(icon1)
        self.actionDakaiexcel.setObjectName(_fromUtf8("actionDakaiexcel"))
        self.actionGuanyuruanjian = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/pic/drill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuanyuruanjian.setIcon(icon2)
        self.actionGuanyuruanjian.setObjectName(_fromUtf8("actionGuanyuruanjian"))
        self.menuWenjian.addAction(self.actionDakaitupian)
        self.menuWenjian.addAction(self.actionDakaiexcel)
        self.menuBangzhu.addAction(self.actionGuanyuruanjian)
        self.menuBar.addAction(self.menuWenjian.menuAction())
        self.menuBar.addAction(self.menuBangzhu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", u"文强海事", None))
        self.pushButton.setText(_translate("MainWindow", u"查看天气", None))
        self.pushButton_2.setText(_translate("MainWindow", u"语音输入", None))
        self.radioButton.setText(_translate("MainWindow", u"汉译英", None))
        self.radioButton_2.setText(_translate("MainWindow", u"英译汉", None))
        self.pushButton_3.setText(_translate("MainWindow", u"提交单词", None))
        self.pushButton_4.setText(_translate("MainWindow", u"清除显示屏", None))
        self.pushButton_5.setText(_translate("MainWindow", u"选择图像", None))
        self.pushButton_6.setText(_translate("MainWindow", u"图像处理", None))
        self.pushButton_7.setText(_translate("MainWindow", u"音乐", None))
        self.pushButton_8.setText(_translate("MainWindow", u"tingzhi", None))
        self.label.setText(_translate("MainWindow", u"关键词", None))
        self.pushButton_11.setText(_translate("MainWindow", u"开始搜索", None))
        self.pushButton_12.setText(_translate("MainWindow", u"浏览文件夹", None))
        self.menuWenjian.setTitle(_translate("MainWindow", u"文件", None))
        self.menuBangzhu.setTitle(_translate("MainWindow", u"帮助", None))
        self.actionDakaitupian.setText(_translate("MainWindow", u"打开图片", None))
        self.actionDakaiexcel.setText(_translate("MainWindow", u"打开excel", None))
        self.actionGuanyuruanjian.setText(_translate("MainWindow", u"关于软件", None))

import mysou_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

